apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: web
    name: in-cluster
  project: default
  source:
    path : nginx-helm-dir
    repoURL: https://github.com/vjwilson1987/nginx-helm.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
