apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: web
    name: in-cluster
  project: default
  source:
    path : .
    repoURL: https://github.com/vjwilson1987/nginx-helm.git
    targetRevision: HEAD
    plugin:
      env:
      - name: HELMFILE_GLOBAL_OPTIONS
        value: --file helmfile.yaml  
      name: helmfile
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
